"""
Thinness certificate for Sp(6) hypergeometric monodromy: case C-32.


    alpha = (0, 0, 0, 0, 1/6, 5/6)
    beta  = (1/4, 3/4, 1/12, 5/12, 7/12, 11/12)


Background
----------

Beukers and Heckman classify the hypergeometric monodromy groups
Gamma(alpha, beta) = <A, B> generated by the companion matrices of

    f(x) = prod_j (x - exp(2 pi i alpha_j))
         = (x - 1)^4 Phi_6(x)
         = x^6 - 5 x^5 + 11 x^4 - 14 x^3 + 11 x^2 - 5 x + 1

    g(x) = prod_k (x - exp(2 pi i beta_k))
         = Phi_4(x) Phi_12(x)
         = x^6 + 1.

Case C-32 was one of the three cases left open by

    [BDN-thin]  Bajpai, Dona, Nitsche.
                Thin monodromy in Sp(4) and Sp(6).
                J. Algebra 664 (2025), 348-361. arXiv:2112.12111v3.

The companion matrices used here are the low-degree-first companion matrices.
They preserve an integral alternating form Omega of determinant 64, so the
natural ambient arithmetic group is Sp_Omega(Z).


Criterion
---------

This script verifies an exact projective ping-pong certificate.  It is not an
arithmeticity witness of the C-47/C-55 kind.  Instead it proves that Gamma is
virtually free, hence infinite index in the ambient arithmetic symplectic
group.

The proof works after a rational change of basis P.  In the new basis,

    S = P^{-1} B P

is a signed cyclic shift with S^6 = -I, and

    T = P^{-1} (B A^{-1}) P

is the rank-one transvection

    T(y0,...,y5) = (y0 + 5 y1 + 11 y2 + 14 y3 + 11 y4 + 5 y5,
                    y1,...,y5).

There is also an involution E satisfying

    E^2 = I,    E S E = S^{-1},    E T E = T^{-1}.

The ping-pong domain is built from a rational polyhedral cone

    K = { y in R^6 : H y >= 0 },

where H is the 77 x 6 integer matrix below.  Let

    X^+ = P(K^o),       X^- = E X^+,       X = X^+ union X^-,
    Y   = union_{k=1}^5 S^k X

in real projective space.  The rows y0 +/- yi, i=1,...,5, are included in H,
so K^o lies in the projective dominance chamber |y0| > |yi|.  Since S is a
signed cyclic shift, X and Y are projectively disjoint.

It remains to verify the plus-side branch inclusions

    G_i K subset K,   i = 0,...,10,

for

    T^{-1},
    T^{-1}S,       T^{-1}S E,
    -T^{-1}S^2,   -T^{-1}S^2 E,
    T^{-1}S^3,     T^{-1}S^3 E,
    -T^{-1}S^4,   -T^{-1}S^4 E,
    T^{-1}S^5,     T^{-1}S^5 E.

The signs are projectively harmless.  They only keep all branch images in the
same affine cone chart.


What this script verifies
-------------------------

    (a) The original companion matrices A and B preserve the displayed
        non-degenerate integral alternating form Omega.

    (b) The rational u-basis has determinant -64 and puts B, T = B A^{-1},
        and E into the claimed normal forms.

    (c) The cone K has no lineality, has non-empty interior, and its interior
        lies in the dominance chamber.

    (d) All eleven branch maps carry K into K.  This is checked exactly by
        converting the H-representation of K to exact extremal rays using
        cdd.gmp, then testing H G_i r >= 0 for every extremal ray r.

    (e) The conjugates S^i (T - I) S^{-i} generate the full Lie algebra
        sp_Q over Q.  This gives an exact Zariski-density check.

The final mathematical conclusion is that the projective group is

    <Tbar, Sbar> ~= Z * C_6,

and the original linear group is the central -I amalgam

    (Z x C_2) *_C_2 C_12.

This group has the Haagerup property.  Since any finite-index subgroup of the
ambient Sp(6)-arithmetic lattice has Kazhdan property (T), Gamma is infinite
index.  Together with (e), this proves that C-32 is thin.


Dependencies
------------

The C-47/C-55 witness scripts need only the Python standard library.  This
script additionally needs cdd.gmp for exact rational polyhedral conversion.
No floating-point arithmetic is used.
"""

from fractions import Fraction

try:
    import cdd.gmp as cdd
except ImportError as exc:
    raise SystemExit(
        "This verifier needs cdd.gmp for exact rational cone conversion. "
        "In this workspace run it with .venv-polyhedra/Scripts/python.exe."
    ) from exc


# ------------------------------------------------------------------
# Case data
# ------------------------------------------------------------------

CASE_LABEL = "C-32"
ALPHA = "(0, 0, 0, 0, 1/6, 5/6)"
BETA = "(1/4, 3/4, 1/12, 5/12, 7/12, 11/12)"

# Coefficient lists of f and g, low-degree first:
#   f = 1 - 5x + 11x^2 - 14x^3 + 11x^4 - 5x^5 + x^6
#   g = 1 + x^6
F_COEFFS = [1, -5, 11, -14, 11, -5, 1]
G_COEFFS = [1, 0, 0, 0, 0, 0, 1]

DIM = 6


# ------------------------------------------------------------------
# Exact integer / rational matrix utilities
# ------------------------------------------------------------------

def companion(coeffs):
    """Companion matrix of a monic polynomial given coeffs low-to-high."""
    n = len(coeffs) - 1
    M = [[0] * n for _ in range(n)]
    for i in range(1, n):
        M[i][i - 1] = 1
    for i in range(n):
        M[i][-1] = -coeffs[i]
    return M


def eye(n):
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def zero(n, m):
    return [[0 for _ in range(m)] for _ in range(n)]


def mm(X, Y):
    n, k = len(X), len(Y)
    m = len(Y[0])
    return [
        [sum(X[i][p] * Y[p][j] for p in range(k)) for j in range(m)]
        for i in range(n)
    ]


def mv(M, v):
    return [sum(M[i][j] * v[j] for j in range(len(v))) for i in range(len(M))]


def msub(X, Y):
    return [[X[i][j] - Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]


def madd(X, Y):
    return [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]


def mneg(X):
    return [[-x for x in row] for row in X]


def transpose(M):
    return [[M[j][i] for j in range(len(M))] for i in range(len(M[0]))]


def equal(X, Y):
    return all(
        X[i][j] == Y[i][j]
        for i in range(len(X))
        for j in range(len(X[0]))
    )


def inv_matrix(M, integral=False):
    """Inverse of an invertible matrix over Q; optionally assert integrality."""
    n = len(M)
    aug = [
        [Fraction(M[i][j]) for j in range(n)]
        + [Fraction(1 if i == j else 0) for j in range(n)]
        for i in range(n)
    ]
    for c in range(n):
        p = next((r for r in range(c, n) if aug[r][c] != 0), None)
        if p is None:
            raise AssertionError("matrix is singular")
        aug[c], aug[p] = aug[p], aug[c]
        f = aug[c][c]
        aug[c] = [x / f for x in aug[c]]
        for r in range(n):
            if r != c and aug[r][c] != 0:
                f = aug[r][c]
                aug[r] = [x - f * y for x, y in zip(aug[r], aug[c])]
    out = []
    for i in range(n):
        row = []
        for j in range(n):
            x = aug[i][n + j]
            if integral:
                assert x.denominator == 1, "non-integral inverse"
                x = int(x)
            row.append(x)
        out.append(row)
    return out


def to_int_matrix(M, label):
    out = []
    for row in M:
        out_row = []
        for x in row:
            x = Fraction(x)
            assert x.denominator == 1, f"{label} has non-integral entry {x}"
            out_row.append(int(x))
        out.append(out_row)
    return out


def mpow(M, exponent):
    if exponent < 0:
        return mpow(inv_matrix(M), -exponent)
    result = eye(len(M))
    base = M
    e = exponent
    while e:
        if e & 1:
            result = mm(base, result)
        base = mm(base, base)
        e >>= 1
    return result


def det_via_elim(M):
    """Determinant via exact elimination; works for integer or Fraction input."""
    n = len(M)
    M = [[Fraction(x) for x in row] for row in M]
    sign = Fraction(1)
    for c in range(n):
        p = next((i for i in range(c, n) if M[i][c] != 0), None)
        if p is None:
            return Fraction(0)
        if p != c:
            M[c], M[p] = M[p], M[c]
            sign = -sign
        for i in range(c + 1, n):
            f = M[i][c] / M[c][c]
            M[i] = [M[i][j] - f * M[c][j] for j in range(n)]
    d = sign
    for i in range(n):
        d *= M[i][i]
    return d


def row_dot(row, vector):
    return sum(row[i] * vector[i] for i in range(len(vector)))


def rank_rows(rows):
    R = [[Fraction(x) for x in row] for row in rows if any(x != 0 for x in row)]
    if not R:
        return 0
    nrows = len(R)
    ncols = len(R[0])
    r = 0
    for c in range(ncols):
        if r >= nrows:
            break
        p = next((i for i in range(r, nrows) if R[i][c] != 0), None)
        if p is None:
            continue
        R[r], R[p] = R[p], R[r]
        f = R[r][c]
        R[r] = [x / f for x in R[r]]
        for i in range(nrows):
            if i != r and R[i][c] != 0:
                f = R[i][c]
                R[i] = [x - f * y for x, y in zip(R[i], R[r])]
        r += 1
    return r


def flatten(M):
    return [x for row in M for x in row]


def rank_matrices(mats):
    return rank_rows([flatten(M) for M in mats])


def cdd_extreme_rays_from_H(H):
    """Exact extremal rays of K = {y : H y >= 0}."""
    inequalities = [[Fraction(0)] + [Fraction(x) for x in row] for row in H]
    mat = cdd.matrix_from_array(inequalities, rep_type=cdd.RepType.INEQUALITY)
    poly = cdd.polyhedron_from_matrix(mat)
    generators = cdd.copy_generators(poly)
    rays = []
    lines = []
    lin_set = set(generators.lin_set)
    for idx, row in enumerate(generators.array):
        vector = tuple(Fraction(x) for x in row[1:])
        if idx in lin_set:
            lines.append(vector)
        elif any(vector):
            rays.append(vector)
    return rays, lines


def min_H_on_vectors(H, vectors):
    return min(row_dot(row, vector) for row in H for vector in vectors)


# ------------------------------------------------------------------
# Original companion-basis data
# ------------------------------------------------------------------

A = companion(F_COEFFS)
B = companion(G_COEFFS)
Ai = inv_matrix(A, integral=True)
Bi = inv_matrix(B, integral=True)
I6 = eye(DIM)

T0 = mm(B, Ai)
T0i = inv_matrix(T0, integral=True)

P_REV = [[1 if i + j == DIM - 1 else 0 for j in range(DIM)] for i in range(DIM)]
E0 = mm(B, P_REV)

OMEGA0 = [
    [0, 13, 22, 25, 22, 13],
    [-13, 0, 13, 22, 25, 22],
    [-22, -13, 0, 13, 22, 25],
    [-25, -22, -13, 0, 13, 22],
    [-22, -25, -22, -13, 0, 13],
    [-13, -22, -25, -22, -13, 0],
]


# u_i = (-1)^i B^i t0, where t0 spans Im(T0 - I).
e0 = [[1], [0], [0], [0], [0], [0]]
t0_col = msub(T0, I6)
t0 = [t0_col[i][0] for i in range(DIM)]
P_BASIS_COLS = []
for i in range(DIM):
    col = mv(mpow(B, i), t0)
    if i % 2:
        col = [-x for x in col]
    P_BASIS_COLS.append(col)
P_BASIS = [[P_BASIS_COLS[j][i] for j in range(DIM)] for i in range(DIM)]
P_INV = inv_matrix(P_BASIS)


# ------------------------------------------------------------------
# Normal-form data in the u-basis
# ------------------------------------------------------------------

S = to_int_matrix(mm(mm(P_INV, B), P_BASIS), "S")
T = to_int_matrix(mm(mm(P_INV, T0), P_BASIS), "T")
T_INV = to_int_matrix(inv_matrix(T), "T^-1")
E = to_int_matrix(mm(mm(P_INV, E0), P_BASIS), "E")

EXPECTED_S = [
    [0, 0, 0, 0, 0, 1],
    [-1, 0, 0, 0, 0, 0],
    [0, -1, 0, 0, 0, 0],
    [0, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, 0],
    [0, 0, 0, 0, -1, 0],
]

EXPECTED_T = [
    [1, 5, 11, 14, 11, 5],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
]

EXPECTED_E = [
    [1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, -1],
    [0, 0, 0, 0, -1, 0],
    [0, 0, 0, -1, 0, 0],
    [0, 0, -1, 0, 0, 0],
    [0, -1, 0, 0, 0, 0],
]

Q = [
    [0, 5, 11, 14, 11, 5],
    [-5, 0, 5, 11, 14, 11],
    [-11, -5, 0, 5, 11, 14],
    [-14, -11, -5, 0, 5, 11],
    [-11, -14, -11, -5, 0, 5],
    [-5, -11, -14, -11, -5, 0],
]


# ------------------------------------------------------------------
# The 77-facet cone K = {y : H y >= 0}
# ------------------------------------------------------------------

H = [
    [1, -1, 0, 0, 0, 0],
    [187, 676, 1105, 1045, 556, 127],
    [17, 66, 113, 111, 62, 15],
    [1, 4, 7, 7, 4, 1],
    [6, 11, 14, 11, 5, 1],
    [259, 952, 1573, 1501, 808, 187],
    [19, 52, 73, 61, 29, 6],
    [343, 1276, 2125, 2041, 1108, 259],
    [43, 136, 205, 180, 89, 19],
    [439, 1648, 2761, 2665, 1456, 343],
    [79, 268, 422, 384, 196, 43],
    [127, 447, 722, 673, 352, 79],
    [1, 1, 0, 0, 0, 0],
    [11, 42, 71, 69, 38, 9],
    [4, 11, 14, 11, 5, 1],
    [9, 30, 45, 39, 19, 4],
    [15, 54, 87, 80, 41, 9],
    [21, 78, 130, 124, 66, 15],
    [27, 101, 170, 165, 90, 21],
    [1, 0, -1, 0, 0, 0],
    [5, 19, 32, 31, 17, 4],
    [1, 0, 1, 0, 0, 0],
    [1, 0, 0, -1, 0, 0],
    [1, 0, 0, 1, 0, 0],
    [9, 34, 57, 55, 30, 7],
    [1, 0, 0, 0, -1, 0],
    [4, 15, 25, 24, 13, 3],
    [1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, -1],
    [1, 0, 0, 0, 0, 1],
    [7, 26, 43, 41, 22, 5],
    [0, -5, -11, -14, -11, -5],
    [4, -1, -5, -11, -14, -11],
    [21, 49, 67, 58, 31, 4],
    [56, 164, 236, 200, 101, 21],
    [10, 14, 11, 5, 1, -5],
    [36, 99, 135, 109, 55, 10],
    [81, 261, 395, 341, 170, 36],
    [10, 5, -1, -5, -11, -14],
    [45, 111, 145, 121, 64, 10],
    [114, 350, 509, 431, 215, 45],
    [220, 745, 1165, 1039, 525, 114],
    [13, 11, 5, 1, -5, -11],
    [54, 138, 181, 148, 76, 13],
    [132, 413, 608, 518, 257, 54],
    [4, 1, -5, -11, -14, -11],
    [19, 49, 67, 58, 31, 4],
    [46, 142, 208, 178, 91, 19],
    [88, 298, 466, 415, 211, 46],
    [4, 11, 14, 11, 5, -1],
    [9, 30, 45, 39, 21, 4],
    [15, 54, 87, 78, 41, 9],
    [21, 78, 132, 124, 66, 15],
    [259, -187, -808, -1501, -1573, -952],
    [19, -17, -70, -125, -127, -74],
    [343, -259, -1108, -2041, -2125, -1276],
    [43, -19, -89, -180, -205, -136],
    [439, -343, -1456, -2665, -2761, -1648],
    [79, -43, -196, -384, -422, -268],
    [268, 79, -43, -196, -384, -422],
    [547, -439, -1852, -3373, -3481, -2068],
    [127, -79, -352, -673, -722, -447],
    [13, -11, -46, -83, -85, -50],
    [9, -4, -19, -39, -45, -30],
    [15, -9, -41, -80, -87, -54],
    [54, 15, -9, -41, -80, -87],
    [36, -10, -55, -109, -135, -99],
    [81, -36, -170, -341, -395, -261],
    [496, 144, -81, -369, -721, -793],
    [114, -45, -215, -431, -509, -350],
    [132, -54, -257, -518, -608, -413],
    [88, -46, -211, -415, -466, -298],
    [9, -4, -21, -39, -45, -30],
    [15, -9, -41, -78, -87, -54],
    [54, 15, -9, -41, -78, -87],
    [21, -15, -66, -124, -132, -78],
    [78, 21, -15, -66, -124, -132],
]

DOMINANCE_ROWS = [
    [1, -1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0],
    [1, 0, -1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0],
    [1, 0, 0, -1, 0, 0],
    [1, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, -1, 0],
    [1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, -1],
    [1, 0, 0, 0, 0, 1],
]

SEED_RAYS = [
    [1, 0, 0, 0, 0, 0],
    [5, -1, 0, 0, 0, 0],
    [11, 0, -1, 0, 0, 0],
    [14, 0, 0, -1, 0, 0],
    [11, 0, 0, 0, -1, 0],
    [5, 0, 0, 0, 0, -1],
]


# ------------------------------------------------------------------
# Exact checks
# ------------------------------------------------------------------

def branch_maps():
    out = [("T^-1", T_INV)]
    for k in range(1, 6):
        eps = 1 if k % 2 == 1 else -1
        base = mm(T_INV, mpow(S, k))
        if eps == -1:
            base = mneg(base)
        out.append((f"{'-' if eps == -1 else ''}T^-1 S^{k}", base))

        with_e = mm(mm(T_INV, mpow(S, k)), E)
        if eps == -1:
            with_e = mneg(with_e)
        out.append((f"{'-' if eps == -1 else ''}T^-1 S^{k} E", with_e))
    return out


def verify_branch_inclusions(rays):
    minima = {}
    for name, G in branch_maps():
        min_value = None
        for ray_index, ray in enumerate(rays):
            image = mv(G, ray)
            for row_index, row in enumerate(H):
                value = row_dot(row, image)
                min_value = value if min_value is None else min(min_value, value)
                assert value >= 0, (
                    f"{name}K subset K failed on ray {ray_index}, "
                    f"facet {row_index}, value {value}"
                )
        minima[name] = min_value
    return minima


def lie_algebra_dimension():
    """Lie algebra generated by S^i (T-I) S^{-i}, checked over Q."""
    basis = []

    def add_to_basis(M):
        r0 = rank_matrices(basis)
        r1 = rank_matrices(basis + [M])
        if r1 > r0:
            basis.append(M)
            return True
        return False

    N = msub(T, I6)
    S_inv = inv_matrix(S, integral=True)
    for i in range(6):
        add_to_basis(mm(mm(mpow(S, i), N), mpow(S_inv, i)))

    changed = True
    while changed:
        changed = False
        current = list(basis)
        for X in current:
            for Y in current:
                if add_to_basis(msub(mm(X, Y), mm(Y, X))):
                    changed = True

    return basis


def main():
    print("=" * 72)
    print(f"Thinness certificate for Sp(6) hypergeometric case {CASE_LABEL}")
    print("=" * 72)
    print(f"  alpha = {ALPHA}")
    print(f"  beta  = {BETA}")
    print()

    # (a) Original ambient symplectic form.
    assert equal(mm(mm(transpose(A), OMEGA0), A), OMEGA0), "A does not preserve Omega0"
    assert equal(mm(mm(transpose(B), OMEGA0), B), OMEGA0), "B does not preserve Omega0"
    det_omega = det_via_elim(OMEGA0)
    assert det_omega == 64, f"unexpected det(Omega0) = {det_omega}"
    print("(a) Ambient form verified")
    print(f"    det(Omega0) = {det_omega}")
    print("    A^T Omega0 A = Omega0 and B^T Omega0 B = Omega0")

    # (b) Normal form.
    det_p = det_via_elim(P_BASIS)
    assert det_p == -64, f"unexpected det(P) = {det_p}"
    assert t0 == [0, 5, -11, 14, -11, 5], f"unexpected t0 = {t0}"
    assert equal(S, EXPECTED_S), "S normal form mismatch"
    assert equal(T, EXPECTED_T), "T normal form mismatch"
    assert equal(E, EXPECTED_E), "E normal form mismatch"
    assert equal(mpow(S, 6), mneg(I6)), "S^6 != -I"
    assert equal(mpow(S, 12), I6), "S^12 != I"
    assert equal(mm(E, E), I6), "E^2 != I"
    assert equal(mm(mm(E, S), E), inv_matrix(S, integral=True)), "E S E != S^-1"
    assert equal(mm(mm(E, T), E), T_INV), "E T E != T^-1"
    assert equal(mm(mm(transpose(S), Q), S), Q), "S does not preserve Q"
    assert equal(mm(mm(transpose(T), Q), T), Q), "T does not preserve Q"
    assert det_via_elim(Q) == 64, "unexpected det(Q)"
    assert equal(mm(mm(transpose(P_BASIS), OMEGA0), P_BASIS), [[4 * x for x in row] for row in Q])
    print("(b) Normal form verified")
    print(f"    t0 = {tuple(t0)}")
    print(f"    det(P) = {det_p}")
    print("    S is signed cyclic, S^6 = -I, S^12 = I")
    print("    T is the stated transvection, and E conjugates S,T to S^-1,T^-1")

    # (c) Cone geometry.
    assert len(H) == 77, f"expected 77 rows in H, got {len(H)}"
    H_rows = {tuple(row) for row in H}
    missing = [row for row in DOMINANCE_ROWS if tuple(row) not in H_rows]
    assert not missing, f"missing dominance rows: {missing}"

    z = [47, -1, -1, -1, -1, -1]
    z_min = min(row_dot(row, z) for row in H)
    assert z_min > 0, "z is not a strict interior point of K"

    rays, lines = cdd_extreme_rays_from_H(H)
    assert len(lines) == 0, "K has lineality"
    assert rays, "K has no extremal rays"

    interior = [sum(ray[i] for ray in rays) for i in range(DIM)]
    interior_min = min(row_dot(row, interior) for row in H)
    dominance_min = min(row_dot(row, interior) for row in DOMINANCE_ROWS)
    seed_min = min_H_on_vectors(H, SEED_RAYS)
    assert interior_min > 0, "extreme-ray interior point is not strict"
    assert dominance_min > 0, "K interior is not in the open dominance chamber"
    assert seed_min >= 0, "seed cone is not contained in K"
    print("(c) Cone K verified")
    print(f"    H has {len(H)} rows")
    print(f"    cdd.gmp found {len(rays)} exact extremal rays and {len(lines)} lines")
    print(f"    strict interior witness min(H z) = {z_min}")
    print(f"    seed cone min(H r) = {seed_min}")

    # (d) Branch invariance.
    minima = verify_branch_inclusions(rays)
    print("(d) Branch inclusions verified")
    print(f"    checked {len(minima)} maps against {len(rays)} extremal rays")
    for name, value in minima.items():
        print(f"    min H({name})r = {value}")

    # (e) Zariski-density sanity check.
    lie_basis = lie_algebra_dimension()
    assert len(lie_basis) == 21, f"Lie algebra dimension is {len(lie_basis)}, not 21"
    for X in lie_basis:
        assert equal(madd(mm(transpose(X), Q), mm(Q, X)), zero(6, 6)), "Lie basis left sp_Q"
    print("(e) Zariski-density Lie algebra check verified")
    print("    dim Lie<S^i(T-I)S^-i> = 21 = dim sp_6")

    print()
    print("=" * 72)
    print("All exact checks passed.")
    print()
    print("The cone K gives projective ping-pong for <Tbar, Sbar>:")
    print("    <Tbar, Sbar> ~= Z * C_6.")
    print("Lifting through the central element -I gives")
    print("    <T, S> ~= (Z x C_2) *_C_2 C_12.")
    print("This group has the Haagerup property and is infinite, so it cannot")
    print("be finite index in the ambient Sp(6)-arithmetic lattice, which has")
    print("property (T).  With the Lie algebra check above, C-32 is thin.")
    print("=" * 72)


if __name__ == "__main__":
    main()
