"""
Arithmeticity witness for Sp(6) hypergeometric monodromy: case C-55.

    alpha = (0, 0, 1/8, 3/8, 5/8, 7/8)
    beta  = (1/2, 1/2, 1/12, 5/12, 7/12, 11/12)


Background
----------

Beukers and Heckman (Invent. Math. 95, 1989) classify hypergeometric
monodromy groups Gamma(alpha, beta) = <A, B> generated by the companion
matrices of

    f(x) = prod_j (x - exp(2 pi i alpha_j))    -- here (x-1)^2 (x^4 + 1)
    g(x) = prod_k (x - exp(2 pi i beta_k))     -- here (x+1)^2 Phi_12(x)

Up to scalar shift and primitivity there are 458 such groups in Sp(6, Z).
For each, the question (Sarnak / Katz) is whether Gamma is arithmetic
(finite index in Sp_Omega(Z)) or thin (infinite index).

Case C-55 was one of three left open by

    [BDN-thin]  Bajpai, Dona, Nitsche.
                Thin monodromy in Sp(4) and Sp(6).
                J. Algebra 664 (2025), 348-361. arXiv:2112.12111v3, Table 3.

The other two open cases are C-32 and C-47.


Criterion
---------

We use the arithmeticity criterion of

    [BDN-arith] Bajpai, Dona, Nitsche.
                Arithmetic monodromy in Sp(2n).
                Groups Geom. Dyn. 20 (2026), no. 1. arXiv:2209.07402.

restated:

    Lemma 1 [BDN-arith].  For n >= 2 let Omega be a non-degenerate
    symplectic form on Q^{2n} integral on Z^{2n} and let
    Gamma <= Sp_Omega(Z) be a Zariski-dense subgroup.  The following are
    equivalent:
        (1) Gamma has finite index in Sp_Omega(Z);
        (2) Gamma contains two transvections X_i = I + lambda_i x_i
            Omega(x_i, .) such that x_1, x_2 are linearly independent and
            Omega-orthogonal (i.e. <X_1, X_2> ~= Z^2).


What this script verifies
-------------------------

Take T = A^{-1} B (a unipotent transvection in Gamma whenever the leading
coefficient of f - g is nonzero) and gamma the witness word in WITNESS
below.  Set X_1 = T, X_2 = gamma T gamma^{-1}; both lie in Gamma.

By [BDN-arith] Lemma 1 it suffices to verify:

    (a)  A and B preserve a common non-degenerate antisymmetric form Omega,
         so Gamma <= Sp_Omega(Z) makes sense.  We solve A^T Omega A = Omega,
         B^T Omega B = Omega for antisymmetric Omega over Q.

    (b)  T - I has rank 1 and T is unipotent, so T is a transvection.

    (c)  T and gamma T gamma^{-1} commute as elements of GL(6, Z).  This is
         equivalent to Omega-orthogonality of their directions and is what
         makes <X_1, X_2> abelian.  Checked directly at the matrix level.

    (d)  The directions x_1 and x_2 of T - I and (gamma T gamma^{-1}) - I
         are linearly independent.  Together with (c) and the unipotence
         of both X_i this forces <X_1, X_2> ~= Z^2.

    (e)  Omega(x_1, x_2) = 0 directly from the explicit Omega found in (a).
         Redundant given (a) and (c) but a useful sanity check that the
         Omega we recovered is the one for which T and gamma T gamma^{-1}
         are symplectic transvections.

Zariski-density of Gamma in Sp_Omega is supplied by Beukers-Heckman
(Theorem 6.5) for all 458 cyclotomic primitive pairs, so we do not
re-derive it.

Run with python3, no external dependencies.  All arithmetic is exact
over Z (with fractions.Fraction used only inside the linear-algebra
helpers that solve A^T Omega A = Omega and invert A, B).
"""

from fractions import Fraction


# ------------------------------------------------------------------
# Case data
# ------------------------------------------------------------------

CASE_LABEL = "C-55"
ALPHA = "(0, 0, 1/8, 3/8, 5/8, 7/8)"
BETA  = "(1/2, 1/2, 1/12, 5/12, 7/12, 11/12)"

# Coefficient lists of f and g, low-degree first:
#   f = 1 - 2x + x^2 + x^4 - 2x^5 + x^6
#   g = 1 + 2x      - 2x^3      + 2x^5 + x^6
F_COEFFS = [1, -2, 1, 0, 1, -2, 1]
G_COEFFS = [1, 2, 0, -2, 0, 2, 1]

# Witness word, length 49.
# Convention: "A" = matrix A, "a" = A^{-1}, "B" = matrix B, "b" = B^{-1}.
# Read left-to-right: v -> M_first v -> M_second M_first v -> ...
# As a matrix, gamma = M_last ... M_second M_first.
WITNESS = "baaaabaaaabaaaabaaaabaaaabaaaabaaaaaBABaBABAAbaaB"

INV_LETTER = {"A": "a", "a": "A", "B": "b", "b": "B"}


# ------------------------------------------------------------------
# Exact integer / rational matrix utilities
# ------------------------------------------------------------------

def companion(coeffs):
    """Companion matrix of a monic polynomial given coeffs low-to-high."""
    n = len(coeffs) - 1
    M = [[0] * n for _ in range(n)]
    for i in range(1, n):
        M[i][i - 1] = 1
    for i in range(n):
        M[i][-1] = -coeffs[i]
    return M


def eye(n):
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def mm(X, Y):
    n, k = len(X), len(Y)
    m = len(Y[0])
    return [[sum(X[i][p] * Y[p][j] for p in range(k)) for j in range(m)]
            for i in range(n)]


def msub(X, Y):
    return [[X[i][j] - Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]


def transpose(M):
    return [[M[j][i] for j in range(len(M))] for i in range(len(M[0]))]


def equal(X, Y):
    return all(X[i][j] == Y[i][j]
               for i in range(len(X)) for j in range(len(X[0])))


def free_reduce(text):
    stack = []
    for ch in text:
        if stack and INV_LETTER[ch] == stack[-1]:
            stack.pop()
        else:
            stack.append(ch)
    return "".join(stack)


def inv_int_matrix(M):
    """Inverse of an invertible integer matrix; asserts integral result."""
    n = len(M)
    aug = [[Fraction(M[i][j]) for j in range(n)] +
           [Fraction(1 if i == j else 0) for j in range(n)] for i in range(n)]
    for c in range(n):
        p = next(r for r in range(c, n) if aug[r][c] != 0)
        aug[c], aug[p] = aug[p], aug[c]
        f = aug[c][c]
        aug[c] = [x / f for x in aug[c]]
        for r in range(n):
            if r != c and aug[r][c] != 0:
                f = aug[r][c]
                aug[r] = [x - f * y for x, y in zip(aug[r], aug[c])]
    out = []
    for i in range(n):
        row = []
        for j in range(n):
            x = aug[i][n + j]
            assert x.denominator == 1, "non-integral inverse"
            row.append(int(x))
        out.append(row)
    return out


def is_rank_one(M):
    """If M is rank-one, return (True, column_direction); else (False, None)."""
    n = len(M)
    pi = pj = None
    for i in range(n):
        for j in range(n):
            if M[i][j] != 0:
                pi, pj = i, j
                break
        if pi is not None:
            break
    if pi is None:
        return False, None
    col = [M[i][pj] for i in range(n)]
    row = [M[pi][j] for j in range(n)]
    s = M[pi][pj]
    for i in range(n):
        for j in range(n):
            if M[i][j] * s != col[i] * row[j]:
                return False, None
    return True, col


def is_unipotent(M):
    """Check (M - I)^n == 0 for n = dim."""
    n = len(M)
    N = msub(M, eye(n))
    P = N
    for _ in range(n - 1):
        P = mm(P, N)
    return all(P[i][j] == 0 for i in range(n) for j in range(n))


def collinear(u, w):
    pivot = next((i for i, x in enumerate(w) if x != 0), None)
    if pivot is None:
        return all(x == 0 for x in u)
    return all(u[i] * w[pivot] == w[i] * u[pivot] for i in range(len(u)))


def find_preserved_antisymmetric_form(matrices, n):
    """One nonzero antisymmetric Omega with M^T Omega M = Omega for all
    M in `matrices`, plus the dimension of the solution space.

    Solves the linear system in the upper-triangular antisymmetric
    parameters Omega[i][j], i < j.
    """
    pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]
    idx = {p: k for k, p in enumerate(pairs)}
    nvars = len(pairs)

    rows = []
    for M in matrices:
        for ii in range(n):
            for jj in range(n):
                row = [Fraction(0)] * nvars
                for (a, b), k in idx.items():
                    coef = (Fraction(M[a][ii]) * M[b][jj]
                            - Fraction(M[b][ii]) * M[a][jj])
                    if (ii, jj) == (a, b):
                        coef -= 1
                    elif (ii, jj) == (b, a):
                        coef += 1
                    row[k] = coef
                rows.append(row)

    R = [list(r) for r in rows]
    nr = len(R)
    r = 0
    pivot_cols = []
    for c in range(nvars):
        if r >= nr:
            break
        p = next((i for i in range(r, nr) if R[i][c] != 0), None)
        if p is None:
            continue
        R[r], R[p] = R[p], R[r]
        f = R[r][c]
        R[r] = [x / f for x in R[r]]
        for i in range(nr):
            if i != r and R[i][c] != 0:
                f = R[i][c]
                R[i] = [x - f * y for x, y in zip(R[i], R[r])]
        pivot_cols.append(c)
        r += 1

    nullity = nvars - r
    pivot_set = set(pivot_cols)
    free_cols = [c for c in range(nvars) if c not in pivot_set]
    if not free_cols:
        return None, 0

    sol = [Fraction(0)] * nvars
    fc = free_cols[0]
    sol[fc] = Fraction(1)
    for i, pc in enumerate(pivot_cols):
        sol[pc] = -R[i][fc]

    # Normalize to integer entries by scaling by the lcm of denominators.
    from math import gcd
    def lcm(a, b): return a * b // gcd(a, b) if a and b else (a or b)
    denom_lcm = 1
    for x in sol:
        if x.denominator != 1:
            denom_lcm = lcm(denom_lcm, x.denominator)
    sol = [x * denom_lcm for x in sol]

    Omega = [[Fraction(0)] * n for _ in range(n)]
    for (a, b), k in idx.items():
        Omega[a][b] = sol[k]
        Omega[b][a] = -sol[k]
    return Omega, nullity


def det_via_elim(M):
    """Determinant via elimination; works for integer or Fraction input."""
    n = len(M)
    M = [[Fraction(x) for x in row] for row in M]
    sign = Fraction(1)
    for c in range(n):
        p = next((i for i in range(c, n) if M[i][c] != 0), None)
        if p is None:
            return Fraction(0)
        if p != c:
            M[c], M[p] = M[p], M[c]
            sign = -sign
        for i in range(c + 1, n):
            f = M[i][c] / M[c][c]
            M[i] = [M[i][j] - f * M[c][j] for j in range(n)]
    d = sign
    for i in range(n):
        d *= M[i][i]
    return d


# ------------------------------------------------------------------
# Verification: walk through (a)-(e) of the strategy in the docstring.
# ------------------------------------------------------------------

def main():
    print("=" * 64)
    print(f"Arithmeticity witness for Sp(6) hypergeometric case {CASE_LABEL}")
    print("=" * 64)
    print(f"  alpha   = {ALPHA}")
    print(f"  beta    = {BETA}")
    word = free_reduce(WITNESS)
    assert word == WITNESS, "witness word is not freely reduced"
    print(f"  word    = {WITNESS}")
    print(f"  length  = {len(WITNESS)} (freely reduced)")
    print()

    A  = companion(F_COEFFS)
    B  = companion(G_COEFFS)
    Ai = inv_int_matrix(A)
    Bi = inv_int_matrix(B)
    assert equal(mm(A, Ai), eye(6)) and equal(mm(B, Bi), eye(6))

    T = mm(Ai, B)

    # ------------------------------------------------------------------
    # (a) [BDN-arith] Lemma 1 needs an ambient Sp_Omega(Z).  Beukers-
    #     Heckman guarantees one exists in our cases, but we recover it
    #     explicitly by solving A^T Omega A = Omega, B^T Omega B = Omega
    #     over Q in the antisymmetric parameters.  The solution space is
    #     1-dimensional (as it must be by Schur, since <A, B> is
    #     irreducible) and the resulting Omega is non-degenerate over Q.
    # ------------------------------------------------------------------
    Omega, dim = find_preserved_antisymmetric_form([A, B], 6)
    assert Omega is not None, \
        "(a) no antisymmetric form preserved by A and B"
    assert equal(mm(mm(transpose(A), Omega), A), Omega), \
        "(a) A does not preserve Omega"
    assert equal(mm(mm(transpose(B), Omega), B), Omega), \
        "(a) B does not preserve Omega"
    Omega_int = [[int(x) if x.denominator == 1 else x for x in row]
                 for row in Omega]
    detOmega  = det_via_elim(Omega_int)
    assert detOmega != 0, "(a) Omega is degenerate"
    print(f"(a) Symplectic form Omega found (solution space dim = {dim})")
    for row in Omega_int:
        print(f"      {row}")
    print(f"    det Omega = {detOmega}, "
          f"A^T Omega A = Omega, B^T Omega B = Omega")

    # ------------------------------------------------------------------
    # (b) [BDN-arith] Lemma 1 needs a transvection X_1 in Gamma.  Take T:
    #     T - I = A^{-1}(B - A) has rank 1 because the only nonzero column
    #     of B - A is the last one (carrying the coefficients of g - f),
    #     and T is unipotent because both A and B preserve Omega.
    # ------------------------------------------------------------------
    is_r1, x1 = is_rank_one(msub(T, eye(6)))
    assert is_r1,           "(b) T - I is not rank 1"
    assert is_unipotent(T), "(b) T is not unipotent"
    print(f"(b) T = A^-1 B is a unipotent transvection")
    print(f"    direction x_1 = {x1}")

    # Build gamma as a 6x6 integer matrix from the witness word, and
    # gamma^{-1} from the formal inverse word.  Check consistency.
    ACT = {"A": A, "a": Ai, "B": B, "b": Bi}
    gamma = eye(6)
    for ch in WITNESS:
        gamma = mm(ACT[ch], gamma)
    gamma_inv = eye(6)
    for ch in WITNESS:
        gamma_inv = mm(gamma_inv, ACT[INV_LETTER[ch]])
    assert equal(mm(gamma, gamma_inv), eye(6)), "gamma * gamma^-1 != I"
    print(f"    gamma * gamma^-1 = I (word convention consistent)")

    # X_2 := gamma T gamma^{-1} is a transvection automatically because
    # conjugation preserves rank-1-ness and unipotence.
    T2 = mm(mm(gamma, T), gamma_inv)
    is_r1_2, x2 = is_rank_one(msub(T2, eye(6)))
    assert is_r1_2,          "gamma T gamma^-1 - I is not rank 1"
    assert is_unipotent(T2), "gamma T gamma^-1 is not unipotent"
    print(f"    direction x_2 = {x2}")

    # ------------------------------------------------------------------
    # (c) [BDN-arith] Lemma 1 requires <X_1, X_2> to be Omega-orthogonal,
    #     equivalently: X_1 and X_2 commute.  Check this directly at the
    #     integer-matrix level, with no reference to Omega.
    # ------------------------------------------------------------------
    assert equal(mm(T, T2), mm(T2, T)), \
        "(c) T and gamma T gamma^-1 do not commute"
    print(f"(c) T and gamma T gamma^-1 commute as integer matrices")

    # ------------------------------------------------------------------
    # (d) [BDN-arith] Lemma 1 requires linear independence of x_1 and x_2.
    #     With (c) and the unipotence of X_1, X_2, this gives
    #     <X_1, X_2> ~= Z^2.
    # ------------------------------------------------------------------
    assert not collinear(x1, x2), "(d) x_1 and x_2 are collinear"
    print(f"(d) x_1 and x_2 are linearly independent")

    # ------------------------------------------------------------------
    # (e) Sanity check: Omega(x_1, x_2) = 0 from the explicit Omega.
    # ------------------------------------------------------------------
    omega_pair = sum(Omega[i][j] * x1[i] * x2[j]
                     for i in range(6) for j in range(6))
    assert omega_pair == 0, f"(e) Omega(x_1, x_2) = {omega_pair} != 0"
    print(f"(e) Omega(x_1, x_2) = 0    (Omega-orthogonal directions)")

    # (f) Zariski-density of Gamma in Sp_Omega is Beukers-Heckman; not
    #     computed here.

    print()
    print("=" * 64)
    print("All checks (a)-(e) passed; (f) by Beukers-Heckman.")
    print()
    print("By [BDN-arith] Lemma 1, Gamma(alpha, beta) is arithmetic in")
    print("Sp_Omega(Z).")
    print(f"This was case {CASE_LABEL} of [BDN-thin] Table 3.")
    print("=" * 64)


if __name__ == "__main__":
    main()
